on: push

jobs:
  publish:
    name: Verification of compile projet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install haskell-platform
      - run: stack install HUnit
      - run: make
      - run: make fclean
      - run: make re
      - run: make && ./tests/test.sh
