on: push

jobs:
  publish:
    name: Verification of compile projet
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install haskell-platform
      - run: sudo apt-get install libghc-hunit-dev
      - run: make
      - run: make fclean
      - run: make re
      - run: make tests_run
      - run: make && ./tests/test.sh
